### PR TITLE
Get all tickers

### PR DESCRIPTION
**Pull request by kolya182**
Fixes https://github.com/tiaanduplessis/coinmarketcap-api/issues/16

### CODE REVIEW

**Comment by abhinavk99** [comment]
Thanks, looks great!

**Comment by kolya182** [comment]
How soon it can be available to download from 'npm' ?.

**Comment by abhinavk99** [comment]
Sorry, but I'm not actually the owner of the repo. I help out, but @tiaanduplessis is the one who publishes this library to npm.

**Comment by tiaanduplessis** [comment]
@kolya182 just released v2.2.0 😄

**Pull request merged**
