### PR TITLE
v3.1.1 - Fixed error when an array of currencies is passed into getGlobal and added unit tests

### LINKED ISSUE #53: Fix error when passing in an array of currencies to getGlobal()
Currently, if the parameter is a string or an array, toUpperCase() is called on the parameter, which fails when an array is passed in.

### PR DESCRIPTION
**Pull request by abhinavk99**
Fixes #53 

Added unit tests to improve coverage to 100%

### CODE REVIEW

**Comment by abhinavk99** [comment]
Also, can you update the library on npm to v3.1.1 after this gets merged in (assuming it's ready to merge)?

**Comment by abhinavk99** [comment]
@tiaanduplessis Are you able to look at this sometime? If you're busy, no worries.

**Comment by abhinavk99** [comment]
@tiaanduplessis Bumping again

**Review by tiaanduplessis — APPROVED** [review]

**Comment by tiaanduplessis** [comment]
@abhinavk99 sorry, my notification inbox has been a mess. Will update to v3.1.1 shortly

**Pull request merged**
