### PR TITLE
feat(getIdMap): Add sort parameter

### PR DESCRIPTION
**Pull request by cicoub13**
Hello,

I've added a sort param in getIdMap. Feel free for any feedbacks.

### CODE REVIEW

**Comment by cicoub13** [comment]
I think your CoinMarketCap API Key is expired

**Comment by abhinavk99** [comment]
@tiaanduplessis Just wanted to let you know I replaced the API key in the Travis CI settings to my own to see if that would fix the tests.

Edit: DIdn't fix it for some reason 😕

**Review by abhinavk99 — APPROVED** [review]
Looks good to me, but I want to try fixing the issue in Travis before I merge this. If I can't figure it out, I'll merge it.

**Comment by abhinavk99** [comment]
Turns out you can't run tests from contributors that use environment variables to prevent security leaks. I'm going to download the branch locally and run the tests to make sure everything works, but I don't think your changes will break anything.

**Comment by abhinavk99** [comment]
The tests all passed locally, so I'm merging. Thanks for the PR!

**Comment by abhinavk99** [comment]
@tiaanduplessis I apologize since it says you're busy, but can you update the package on npm to the newest version (v3.1.0) whenever you're available?

**Pull request merged**
