### PR TITLE
Added sort option and fixed fetcher

### PR DESCRIPTION
**Pull request by abhinavk99**
- Added sort param for getTicker
- Changed structure param to be of type String, not Int
- Added fetcher to option for createRequest in getTicker
- Fixed standard errors with not detecting jest's `expect` and `test` by setting standard's environment to jest

I didn't push directly because standard was giving me a bunch of errors with the docs. I think it's best if we change the command in `package.json` so it only lints `index.js`, but I didn't want to change that without asking first.

### CODE REVIEW

**Comment by abhinavk99** [comment]
I just went ahead and changed the command for standard to only cover index.js and test.js. I didn't merge it in case you wanted standard to cover all the js files in the docs.

**Comment by CruiseMan** [comment]
It's not the best practice to put so many changes for different functionality in one PR.

**Comment by abhinavk99** [comment]
Oh sorry I didn't know that. Thanks for the advice.

**Review by tiaanduplessis — APPROVED** [review]

**Review by tiaanduplessis — APPROVED** [review]

**Comment by tiaanduplessis** [comment]
@abhinavk99 looks good. Thanks for the work 😄

**Pull request merged**
